Trait {
	#name : #TRubyProgramNodeVisitor,
	#traits : 'TSmaCCParseNodeVisitor',
	#classTraits : 'TSmaCCParseNodeVisitor classTrait',
	#category : #'GToolkit4Ruby-AST'
}

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAlias: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArray: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArrayReference: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssocSplatArgument: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssociation: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssociationArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBeginBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBinary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBlockArgVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBlockArgument: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBreak: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitCall: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitCase: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitCharacter: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitClass: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitConcatString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitConstPath: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitDefined: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitDynamicSymbol: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitElse: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitElsif: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitEnsureBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitExcludeRange: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitField: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitFile: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitFor: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitHash: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitHeredocDedent: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitIf: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitIfExpression: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitIfMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitInterpolatedExpression: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitKeywordVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitLabel: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitLambda: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitLhsVariables: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitMethod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitModule: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitMultipleAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitNext: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitNumber: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitOptionalVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitParams: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitPart: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitProgram: aNode [
	^ self visitSmaCCParseNode: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRange: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRegex: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRescue: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRescueElseNode: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRescueMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRestVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRetry: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitReturn: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSingletonClass: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSplat: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSplatVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitStatementBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSuperCall: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSymbol: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUnary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUnless: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUnlessMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUntil: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUntilMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitValueList: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitWhen: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitWhile: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitWhileModifier: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitXString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitYield: aNode [
	^ self visitProgram: aNode
]
