Trait {
	#name : #TRubyProgramNodeVisitor,
	#traits : 'TSmaCCParseNodeVisitor',
	#classTraits : 'TSmaCCParseNodeVisitor classTrait',
	#category : #GToolkit4Ruby
}

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArray: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitArrayReference: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssociation: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitAssociationArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBinary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitBlockArgument: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitCall: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitCase: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitClass: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitConstPath: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitDefined: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitElse: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitFile: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitHash: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitHeredocDedent: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitIf: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitIfMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitInterpolatedExpression: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitKeywordVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitLabel: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitLhsVariables: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitMethod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitMultipleAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitNumber: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitParams: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitPart: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitProgram: aNode [
	^ self visitSmaCCParseNode: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitRegex: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitReturn: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSplatVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitStatementBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitSymbol: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUnary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitUnless: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRubyProgramNodeVisitor >> visitWhen: aNode [
	^ self visitProgram: aNode
]
