Trait {
	#name : #TRpRubyProgramNodeVisitor,
	#traits : 'TSmaCCParseNodeVisitor',
	#classTraits : 'TSmaCCParseNodeVisitor classTrait',
	#category : #'GToolkit4Ruby-Ripper-AST'
}

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitAlias: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitArray: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitArrayReference: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitAssocSplatArgument: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitAssociation: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitAssociationArguments: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBeginBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBinary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBlockArgVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBlockArgument: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitBreak: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitCall: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitCase: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitCharacter: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitClass: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitConcatString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitConstPath: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitDefined: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitDynamicSymbol: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitElse: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitElsif: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitEnsureBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitExcludeRange: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitField: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitFile: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitFor: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitHash: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitHeredocDedent: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitIf: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitIfExpression: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitIfMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitInterpolatedExpression: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitKeywordVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitLabel: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitLambda: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitLhsVariables: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitMethod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitModule: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitMultipleAssignment: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitNext: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitNumber: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitOptionalVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitParams: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitPart: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitProgram: aNode [
	^ self visitSmaCCParseNode: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRange: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRegex: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRescue: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRescueElseNode: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRescueMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRestVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitRetry: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitReturn: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitSingletonClass: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitSplat: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitSplatVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitStatementBlock: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitSuperCall: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitSymbol: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitUnary: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitUnless: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitUnlessMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitUntil: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitUntilMod: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitValueList: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitVariable: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitWhen: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitWhile: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitWhileModifier: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitXString: aNode [
	^ self visitProgram: aNode
]

{ #category : #generated }
TRpRubyProgramNodeVisitor >> visitYield: aNode [
	^ self visitProgram: aNode
]
